require("dotenv").config()



module.exports = {
  
    MONGO_USERNAME:process.env.MONGO_USERNAME,
    MONGO_PASSWORD:process.env.MONGO_PASSWORD,
    MONGO_DATABASE_NAME:process.env.MONGO_DATABASE_NAME,
    DARWINBOX_USERNAME:process.env.DARWINBOX_USERNAME,
    DARWINBOX_PASSWORD:process.env.DARWINBOX_PASSWORD,
    DARWINBOX_API_KEY:process.env.DARWINBOX_API_KEY,
    DARWINBOX_DATASET_KEY:process.env.DARWINBOX_DATASET_KEY,
    DARWINBOX_BASE_URL:process.env.DARWINBOX_BASE_URL
} 